version: "3.2"
services:
  collectd:
    image: vasuadari/collectd
    container_name: collectd
    volumes:
      - './collectd:/etc/collectd'
    external_links:
      - 'riemann:riemann'
    networks:
      - monitoring_monitoring

networks:
  monitoring_monitoring:
    external: true
